options:
  mcc:
    type: string
    description: |
      The Mobile Country Code (MCC) of the DU.
    default: "208"
    required: true
  mnc:
    type: string
    description: |
      The Mobile Network Code (MNC) of the DU.
    default: "99"
    required: true
  mnc-length:
    type: string
    description: |
      The length of the Mobile Network Code (MNC) of the DU.
    default: "2"
    required: true
  nssai-sst:
    type: string
    description: |
      The Slice Service Type (SST) of the DU.
    default: "1"
    required: true
  nssai-sd:
    type: string
    description: |
      The Slice Differentiator of the DU.
    default: "000001"
    required: true
